spring:
  application:
    name: HustSocialNetwork

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    url: jdbc:mysql://db:3306/social?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: jolibee1892004
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
     host: mail92112.maychuemail.com
     port: 465
     username: munivers68fe
     password: Bang1892004@
     email: munivers68fe@muniversity.id.vn
     properties:
       mail.smtp.auth: true
       mail.smtp.ssl.enable: true

  data:
    redis:
      host: redis
      port: 6379
      timeout: 6000

jwt:
  secret: 6a915cc818ce759698ca2eaffcd841b2a19a72e3c00b421c38a6e0150c3cfd68
  access-expiration: 86400000
  refresh-expiration: 604800000

server:
  port: 8080

app:
  base-url: https://api.muniversity.id.vn

minio:
  endpoint: https://minio-api.muniversity.id.vn
  credentials:
    accessKey: bangdeptrai
    secretKey: jolibee1892004

oauth:
  client_id: 16daeb59-cec5-469e-886a-69f34976fb3b
  client_secret: nek8Q~canGot9heeQY8HyW3MGEYtq37IMpaIkcTS
